spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.example.myshop: DEBUG